apiVersion: v1
kind: List
items:
- apiVersion: federation.k8s.io/v1alpha1
  kind: FederatedService
  metadata:
    name: mongo
  spec:
    template:
      metadata:
        labels:
          name: mongo
      spec:
        type: LoadBalancer
        ports:
          - port: 27017
            targetPort: 27017
        selector:
          name: mongo
- apiVersion: federation.k8s.io/v1alpha1
  kind: FederatedServicePlacement
  metadata:
    name: mongo
  spec:
    clusternames:
