apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Namespace
  metadata:
    name: pacman
- apiVersion: federation.k8s.io/v1alpha1
  kind: FederatedNamespacePlacement
  metadata:
    name: pacman
  spec:
    clusternames:

